# The URL the site will be built for
base_url = "https://white_koala.gitee.io/koala_blog"

# Site title
title = "Koala Blog"

# Site description
description = "一个使用 Zola 搭建的个人博客"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later by the JavaScript search
build_search_index = false

[markdown]
# Whether to do syntax highlighting
highlight_code = true

# Available languages: https://www.getzola.org/documentation/content/syntax-highlighting/#languages
highlight_theme = "dracula"

[extra]
# Put all your custom variables here
author = "Koala"
