title = "Koala Blog"
description = "一个使用 Zola 搭建的个人博客"
base_url = "https://bjj999.github.io/koala-blog"
theme = "olivine"

compile_sass = true
taxonomies = [{ name = "tags" }]
build_search_index = true

[markdown]
external_links_target_blank = true
smart_punctuation = true

[markdown.highlighting]
theme = "github-dark"

[link_checker]
internal_level = "warn"

[extra]
author = "White_Koala"

[extra.olivine]
journal = true
graph = true
mathjax = false
tikzjax = false
extra_js = []
